baseURL = "https://dailydreamer.me"
title = "dailydreamer"
author = "dailydreamer"
languageCode = "zh-cn"
disqusShortname = "dailydreamer"
googleAnalytics = "UA-75912368-1"

[params]
  description = "dailydreamer的小空间"
  github = "https://github.com/dailydreamer"
  favicon = "avatar.jpg"

[outputs]
  home = ["HTML", "RSS", "JSON"]